### ISSUE TITLE
Versionize tests/rest-api/methods.yml

### ISSUE THREAD

**Issue by mattes** [gambol99/go-marathon#107]
We should probably versionize the marathon mock, so we can eventually test against different marathon versions.

**Comment by timoreimann** [comment]
Are there already different Marathon versions? My understanding is there's only version 2.

**Comment by mattes** [comment]
`v0.11` added `taskStats` for example. v0.10.0 added a complete new endpoint `DELETE /v2/queue/{appId}/delay`.

**Comment by eicca** [comment]
I think we can just keep up with latest marathon updates until it reaches a stable version. I don't see a lot of sense in supporting pre-release versions.

**Comment by timoreimann** [comment]
IIRC, the previous Marathon changes were all non-breaking, feature-adding ones. In that sense, there should be no current need to version.

If/when Marathon decides to do an important breaking change/bring out a new major-version release, we should reconsider. Depending on the concrete change, however, we may be able to support both old and new APIs and thus still need not bother with versioning.

**Comment by eicca** [comment]
@timoreimann :+1:

**Comment by mattes** [comment]
Okay. Closing. :-)
