### ISSUE TITLE
kill Task does not work when scale=true is used. 

### ISSUE THREAD

**Issue by lokeshverizon** [gambol99/go-marathon#112]
KillTask(taskID string, scale bool) (*Task, error)

does not work properly with scale=true. (scale=true) does not take affect. Based on the debugging I found: rest API which is passed is: 
 http://10.1.42.1:19090/v2/apps/appid/tasks/taskid  {"bool":true} 

it should be 
http://162.47.116.88:19090/v2/apps//appid/tasks/taskid?scale=true

As marathon GUI uses kill&scale on task above URL.

**Comment by eicca** [comment]
I can confirm this, marathon expects parameters to be in the url.

I started fixing the bug here: https://github.com/gambol99/go-marathon/compare/master...eicca:refactor-tasks

I'm going to prepare a PR soon.
