### ISSUE TITLE
Add support to (insecure) TLS 

### ISSUE THREAD

**Issue by emilevauge** [gambol99/go-marathon#122]
Hi!
Marathon support [securing its API endpoints via SSL](
https://mesosphere.github.io/marathon/docs/ssl-basic-access-authentication.html).
It would be great to support that in go-marathon.
It would also be useful to add the possibility to accept self-generated certificates in this case:`tls.Config.InsecureSkipVerify`.

**Comment by gambol99** [comment]
Adding the PR #125

**Comment by gambol99** [comment]
@emilevauge you can override the http client if you wish now ... https://github.com/gambol99/go-marathon/blob/master/README.md#custom-http-client ...

**Comment by emilevauge** [comment]
Thanks a lot!
