### ISSUE TITLE
Failure to parse content from error response causes nil error to be returned to caller

### ISSUE THREAD

**Issue by timoreimann** [gambol99/go-marathon#152]
When [parseContent()](https://github.com/gambol99/go-marathon/blob/52466f39391c90839b2a75715d5c5af68b7e7502/error.go#L85) fails, it returns a `(nil, err)` pair to the [call site](https://github.com/gambol99/go-marathon/blob/52466f39391c90839b2a75715d5c5af68b7e7502/client.go#L280). We log the parse error dutifully but also [return](https://github.com/gambol99/go-marathon/blob/52466f39391c90839b2a75715d5c5af68b7e7502/client.go#L285) the (nil) `APIError` copy straight to the user, giving the impression that nothing failed (which is not correct).

We should return an embedded parser error so that callers may at least be able to see the unparsable error.

**Comment by timoreimann** [comment]
After having taken a closer look at the code path at hand, I was surprised to see that we actually return an `APIError` instance that's non-nil. I can't make complete sense out of it yet; the problem can be reduced to the the following sample case: https://play.golang.org/p/cOrHfJURLD

The fix proposal I gave in the issue description should still hold though.

**Comment by seh** [comment]
Related FAQ: [_Why is my nil error value not equal to nil?_](https://golang.org/doc/faq#nil_error)

**Comment by timoreimann** [comment]
@seh That explains it perfectly. I read that part of the FAQ such a long while ago that it totally went off my radar. Thanks for the pointer!
