### ISSUE TITLE
go-marathon does not work with marathon 1.1.1 due to changed deployments/steps schema

### ISSUE THREAD

**Issue by kesselborn** [gambol99/go-marathon#153]
go-marathon does not work correctly anymore with marathon 1.1.1 as the deployments/steps schema was changed.
Up to now it looks more like this is a [marathon bug](https://github.com/mesosphere/marathon/issues/3820) which currently is set to fixed but does not fix the real problem (see [comment on the issue](https://github.com/mesosphere/marathon/issues/3820#issuecomment-222201282) ).
This issue is to track the solution and create a pull request should the new schema be correct. Happy to provide a pull request once the situation is more clear.

**Comment by timoreimann** [comment]
PR would be very much appreciated once the situation has cleared up. :+1:

**Comment by timoreimann** [comment]
(updated the first broken link in the description. Github issue references don't seem to work when used together with custom links)

**Comment by kesselborn** [comment]
@timoreimann oh, thanks

**Comment by timoreimann** [comment]
@kesselborn with #158 being merged, do you think we should  keep this issue open in order to track how mesosphere/marathon#3965 evolves? Or close this one instead and open a new issue if the API changes again?

**Comment by timoreimann** [comment]
Closing now. We can easily open another issue should the API change again.
