### ISSUE TITLE
Tasks endpoint  does not return JSON

### ISSUE THREAD

**Issue by iderdik** [gambol99/go-marathon#16]
For some reason, Marathon does not return JSON for its v2/tasks endpoint. This library expects a JSON response and fails with "failed to unmarshall the response from marathon," when calling client.GetAllTasks().

**Comment by gambol99** [comment]
Could you provide a sample of the json response from your /v2/tasks? .. also which version of Marathon?

**Comment by gambol99** [comment]
Hopefully the recent PR and merge will have fixed the issue [sha: 440265e769585625cbda198bb18f066504dfe877] ... If not, let me know ...

**Comment by iderdik** [comment]
Sorry for late response. The issue still occurs (Marathon version 0.8). Here is the debug output:
```
debug]: apiCall() method: GET, uri: v2/tasks, body:
[debug]: httpCall(): GET, uri: v2/tasks, url: http://xxxxxxxx.net:8080/v2/tasks
[debug]: httpCall: GET, uri: v2/tasks, url: http://xxxxxxxx.net:8080/v2/tasks
[debug]: apiCall() status: 200, content: phpinfoa	80	i-0eb61bf8.xxxxx.net:31002	i-f400463d.xxxxxxxx.net:31003	i-1dec4510.xxxxxxxx.net:31001	i-0eb61bf8.xxxxx.net:31003
phpinfoc	10000	i-f400463d.xxxxx.net:31000	i-0eb61bf8.xxxxx.net:31004	i-f400463d.xxxxx.net:31004	i-1dec4510.xxxxx.net:31004
phpinfod	10001	i-f400463d.xxxxx.net:31001	i-1dec4510.xxxxx.net:31000	i-0eb61bf8.xxxxx.net:31000	i-1dec4510.xxxxx.net:31002
[debug]: apiCall(): failed to unmarshall the response from marathon, error: invalid character 'p' looking for beginning of value
```

The call was made as `Client.AllTasks()`

**Comment by gambol99** [comment]
Hiya ... this should have been fixed in https://github.com/gambol99/go-marathon/commit/440265e769585625cbda198bb18f066504dfe877 .. By default the /v2/tasks endpoint returns text/plain content ...I just need to enforce the accept: json/application header in the request.

**Comment by iderdik** [comment]
Perfect. Thanks!
