### ISSUE TITLE
Configurable marathon uri prefix

### ISSUE THREAD

**Issue by vishr** [gambol99/go-marathon#178]
In our DCOS deployment we have multiple marathon with different names. These names are used in the marathon API URL.

For example:

- `...:9090/service/marathon/v2/deployments`
- `...:9090/service/mon-marathon-service/v2/deployments`

The library uses fixed name `marathon` https://github.com/gambol99/go-marathon/blob/master/client.go#L247. I think it should be configurable to be able to use multiple marathon services.

**Comment by timoreimann** [comment]
@vishr thanks for creating the issue. This sounds like a reasonable request. My proposal would be to extend the configuration so that custom names can be defined.

Happy to review any PR you may want to submit. :-)

**Comment by gambol99** [comment]
hi @vishr does https://github.com/gambol99/go-marathon/issues/179 fix your issue?

**Comment by timoreimann** [comment]
I'll close this issue for now. @vishr, if you think #179 doesn't solve your problem, please don't hesitate to reopen and add more details.

Thanks.
