### ISSUE TITLE
Publish new version tag and define future tag policy

### ISSUE THREAD

**Issue by timoreimann** [gambol99/go-marathon#186]
go-marathon has a single git tag `v0.0.1` which is fairly outdated. I believe we should push another tag now and make it become a habit to do so periodically.

My reasoning is that the Go ecosystem has produced tooling by now which is capable of leveraging and even detecting tag-based semantic versioning. In fact, I noticed the single tag version by running [glide](http://glide.sh/) over our internal code base and seeing how it would offer me to use go-marathon 0.0.1. This gives the impression that this is a fairly recent release, which it isn't.

Although I can't recall clearly anymore, it seems it was me who pushed the single tag back in January, since it's related to one my features. Thus, one option we have is to just delete the tag and continue running without any versions. Following the recent discussions around package management and versioning, however, there [seems to be consensus to bless semantic versioning](https://docs.google.com/document/d/1M4Ldgtxr9vC8wpyTldQe5oUyGN9eb1CeUcJT3N5XaPk) by the Go community in the future. Thus, I think it would be advisable to come into a habit of versioning go-marathon releases regularly.

If we can find agreement on this point, the next question would be whether we should go with a 1.0.0 release or continue working on 0.x.y versions. The former would require a certain sense of stability whereas the latter would allowed us to make additional breaking changes until we are more confident about the API. Given that the majority of changes done over the last few months were of an additive nature (mostly to account for extensions to the Marathon REST API), I believe we are pretty close to a stable 1.0.0. What I would suggest though is to spend a bit of dedicated time going over the code base looking for design deficiencies that we would need to fix through breaking API changes. We could start this effort by tagging the current HEAD with v0.1.0, bumping the minor version as we fix things ([as recommended](http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)), and finalize with the first major release. I don't expect this process to take too many minor releases, but I believe it would be good to have before making any stability promises.

Opinions on this one? @gambol99, what do you think?

**Comment by gambol99** [comment]
Hi @timoreimann ... I'd agree starting from a pre v1.0.0 tags makes sense, glancing through the code recently there's a number of sections where the code looks patchy and would love to clean it up. I think tagging now and raising issues against what we have to fix it.

**Comment by timoreimann** [comment]
@gambol99, sounds good. I can add the tag. Could you create issues for things you have spotted already?

I think it would also be helpful to create a milestone 1.0.0 and associated those issues to it.

**Comment by timoreimann** [comment]
Pushed [tag v1.0.0](https://github.com/gambol99/go-marathon/tree/v0.1.0) and created [milestone v1.0.0](https://github.com/gambol99/go-marathon/milestone/1).

**Comment by timoreimann** [comment]
Closing ticket.

@gambol99, feel free to create milestone 1.0.0 issues and associate accordingly.
