### ISSUE TITLE
HasHealthCheckResults false is not the same as unhealthy

### ISSUE THREAD

**Issue by gomes** [gambol99/go-marathon#189]
There is an misunderstanding about HealthCheckResults usage, as I saw in tasks.go allHealthChecksAlive() bool:
    // check: does the task have a health check result, if NOT, it's because the
        // health of the task hasn't yet been performed, hence we assume it as DOWN

It is incorrect to assume this, Marathon in some situations has trouble to do healthchecks, so you can't have results, but not necessarily the app isn't healthy. For example,when a new leader is elected, Marathon run healthchecks in all tasks, so you start with 0 tasks with HealthCheckResults, but your apps are healthy.

**Comment by timoreimann** [comment]
@gomes thanks for bringing this to our attention.

Is there a way to reliably identify the cases where health checks are missing but we know for sure that the app is healthy? If not, then the best thing we can do is change `allHealthChecksAlive()`'s return type from boolean to a ternary including an _unknown_ state. However, that function is currently only used by `TaskEndpoints()`, which probably shouldn't return anything if we can't reliable tell what an app's health state is, so it would ignore both _unknown_ and _false_ results anyway, making our improvement in precision to `allHealthChecksAlive()` look  obsolete.

Other thoughts on this?

**Comment by gomes** [comment]
Hello @timoreimann 

Actually not, because HealthChecks are not mandatory. My bigger problem is about HasHealthCheckResults() usage in Traefik, I will open an issue there about it too.

I think a method which returns healthy and unknown  state tasks should resolve this issue, because healthcheck results are not persisted. Traefik just did lost all my app's for about 1 minute after a leader change and I received 404 error in a nonstop mode, which was stressful

**Comment by timoreimann** [comment]
@gamos I'm not sure I fully understand yet what part of go-marathon exactly you'd like to see change, and to what extent. Maybe you can be more specific and / or reference that Traefik issue you intend to file in order to see the whole picture. My current thinking is that maybe the resolution of this problem doesn't require any changes to go-marathon but just a proper, domain-specifc interpretation of what a missing health check means. The latter may be within the responsibility of Traefik solely.

I'm not saying that we shouldn't change go-marathon; only that more information seems helpful at this stage.

**Comment by gomes** [comment]
I filled an issue there: https://github.com/containous/traefik/issues/653

What about a method to inform if a task is available or not? So you can remove from this only apps which are unhealthy, but preserves those not tested yet

**Comment by timoreimann** [comment]
@gomes sorry for the delay. I'll do my best to help this issue moving forward.

IIUC, we'd have to distinguish whether a task is healthy, unhealthy, or unknown to be either. For applications coming with a custom health check, the three states would map to the `Alive` property being true, false, or the health check result missing, respectively. For applications without any health check (i.e., the default one), there would only be healthy or unhealthy (depending on whether the task is up and running or not).

Did I get this correctly? If not, please complement/correct. If yes, I'm happy to review any PR you may submit. :-)

**Comment by timoreimann** [comment]
Seems to have been fixed upstream in Traefik, so I'm closing the issue for now. If new use cases for having a ternary result pop up, please comment/reopen.
