### ISSUE TITLE
Unreliable IP retrieval for Event Subscription

### ISSUE THREAD

**Issue by iderdik** [gambol99/go-marathon#19]
client.RegisterSubscription in subscription.go assumes that the interface passed in from the config is unique. On my (and I'm sure most) machines, there is are  IPv6 and IPv4  interfaces with the same name. The matching in the getInterfaceAddress in utils.go will most likely get an unusable address. I'm not sure what the best way to handle this is though :(. Perhaps optionally allow an IP to be explicitly set in the config which puts the onus on the developer to retrieve and use the correct IP?

**Comment by x-cray** [comment]
@gambol99 Did you consider using SSE stream rather? https://mesosphere.github.io/marathon/docs/rest-api.html#event-stream

**Comment by gambol99** [comment]
hiya .. yeah, i saw marathon added the feature a month or so back and looked into using it; i think i stumbled on the same lib [eventsource](https://github.com/donovanhide/eventsource). As yet I've not got around to working on the feature ... a PR would be welcome though :-)

**Comment by x-cray** [comment]
@gambol99 just making some final touches to PR. Will need to add some tests though =)
