### ISSUE TITLE
Docker Container PortMapping Labels

### ISSUE THREAD

**Issue by catherinetcai** [gambol99/go-marathon#190]
Currently, go-marathon doesn't support labels for Docker container portmappings: 

```
"container": {
    "docker": {
      "forcePullImage": false,
      "image": "mesosphere:marathon/latest",
      "network": "BRIDGE",
      "parameters": [
        {
          "key": "name",
          "value": "kdc"
        }
      ],
      "portMappings": [
        {
          "containerPort": 80,
          "hostPort": 0,
          "protocol": "tcp",
          "servicePort": 10019,
          "name": "http",
          **"labels": { "vip": "192.168.0.1:80" }**
        }
      ],
      "privileged": false
    }
```

I think a map should be added on the PortMapping struct to allow for labels to be passed in. These labels are useful for setting VIPs in DCOS.

If you guys find this useful, I already have a fork of go-marathon with these changes.

**Comment by timoreimann** [comment]
Hey @catherinetcai, I believe @Mongey's PR #191 fixed this. I'll close the issue -- if you believe there's still something missing, please don't hesitate to ask for reopening.

Thanks!
