### ISSUE TITLE
If using default config, WaitOnDeployment will wait 138 hours in for loop

### ISSUE THREAD

**Issue by zyfdegh** [gambol99/go-marathon#217]
If I using default config, like [example/application.go](https://github.com/gambol99/go-marathon/blob/master/examples/applications/main.go#L45), it will wait for too long in [waitOnDeployment](https://github.com/gambol99/go-marathon/blob/master/examples/applications/main.go#L106) and got stuck. In fact, it will wait 138h53m20s.

After debugging, we found this issue is caused by [a mistake here](https://github.com/gambol99/go-marathon/blob/master/deployment.go#L154), I think the highlighted line should be

```go
time.Sleep(r.config.PollingWaitTime)
```

In this way, If I set timeout to 800ms like, 

```go
config := marathon.NewDefaultConfig()
config.PollingWaitTime = 800 * time.Millisecond
```

it won't be multiply by 1000000000 [here](https://github.com/gambol99/go-marathon/blob/master/client.go#L215).

WDYT? Please check and confirm this issue. I will push a commit if needed.

**Comment by timoreimann** [comment]
@zyfdegh thanks for the report. You're right that the additional multiplication is the problem.

With regards to fixing this, I think we could just get rid of `marathonClient.pollingWaitTime`: It should be okay to just reference the value from the configuration object. At least, it looks possible to me on first sight.

I have [pushed a branch with a single timeout value only](https://github.com/gambol99/go-marathon/tree/remove-client-polling-param). My tests are looking good so far; if you want to do some additional testing, I'd appreciate.

**Comment by zyfdegh** [comment]
Good job! Lightning speed! I'm looking forward of the branch merged to master.

**Comment by timoreimann** [comment]
Still trying to see if I can improve the testing framework in reasonable time to cover our case.
