### ISSUE TITLE
ipAddress field not found

### ISSUE THREAD

**Issue by yathi-naik** [gambol99/go-marathon#224]
To deploy docker containers onto the overlay network, we have to specify `{"ipAddress": {"network": "$MYNETWORK"}}` in the marathon application definition. But I don't see that in the Application struct. 

https://docs.mesosphere.com/1.8/usage/service-discovery/load-balancing-vips/overlay-networks/

**Comment by timoreimann** [comment]
#223 is about to introduce IP-per-task. We should be able to easily add the network field once it has been merged.
