### ISSUE TITLE
Listing apps with labels

### ISSUE THREAD

**Issue by bobrik** [gambol99/go-marathon#23]
Marathon can filter apps with specific labels: mesosphere/marathon#1416. You can also embed tasks into apps to avoid extra requests with `embed=apps.tasks`.

I propose add an argument to `Marathon.Applications()`, like this:

```go
type ApplicationsOptions struct {
	Embed string
	Cmd   string
	Label string
}
```

I can come up with a PR.

**Comment by bobrik** [comment]
It probably worth thinking how to extend that to other api endpoints that take params.

**Comment by gambol99** [comment]
Have to admit, I'm kinda inclined to provide a generic Params like struct, wrapping a map[string]interface and allow programmer to make the choice adding or not adding options. That way we don't have to add, remove, amend options per endpoint as Marathon evolves and changes it's API; The only danger I foresee down that road would be if the option alters the assumed response (i.e. struct) your expecting to decode into??

**Comment by bobrik** [comment]
Well, `map[string]interface{}` is probably too much, `url.URL.Query()` is `map[string][]string`. I think we can do just `map[string]string` or use some interface that can convert itself to `map[string]string`.

Take a look at [elastic](https://github.com/olivere/elastic/blob/78b87db2a9c53fb29acfaca1c16764d66a7ac519/query.go). I can try to implement something like `Options` and iterate on it in PR. What do you think?

**Comment by gambol99** [comment]
Sounds good to me

**Comment by gambol99** [comment]
closing ... as the changes we're merged
