### ISSUE TITLE
Use http.Client with Timeout for SSE will Cause Subscription Error

### ISSUE THREAD

**Issue by gaopenghigh** [gambol99/go-marathon#237]
go-marathon use the same http.Client for both regular HTTP API requests and SSE subscription:

（https://github.com/gambol99/go-marathon/blob/master/subscription.go#L182）:

```
	// Try to connect to stream, reusing the http client settings
	stream, err := eventsource.SubscribeWith("", r.httpClient, request)
```

If `r.httpClient` have Timeout set, which is needed for normal HTTP API calls, SSE Timeout Error will be raised:
```
[go-marathon] ERROR watch SSE failed: stream ERROR: net/http: request canceled (Client.Timeout exceeded while reading body)
```

**Comment by timoreimann** [comment]
My gut feeling is that we should ignore / disallow the timeout setting on the HTTP client instance when it comes to SSE: That timer covers reading the body, something which (to my understanding) will never finish during an ongoing SSE stream.

**Comment by timoreimann** [comment]
With #297 merged, we now accept another HTTP client specific to SSE subscriptions and return an error if the timeout is set.

Closing issue as resolved.
