### ISSUE TITLE
/ipAddress/discovery/ports missing 

### ISSUE THREAD

**Issue by yathi-naik** [gambol99/go-marathon#241]
There are 2 issues I'm facing,

First Issue:

I'm using the following in my application definition to launch a container on a DCOS overlay network.

```
	application.Container.Docker.Network = "USER"
	application.IPAddressPerTask = &marathon.IPAddressPerTask{
		NetworkName: "dcos",
	}
```
I see the following error,
```
Error: Marathon API error: Invalid JSON (path: '/ipAddress/discovery/ports' errors: error.path.missing)
```

We do not need to specify Discovery and Ports via normal POST to marathon endpoint. 

Second Issue:

With the same definition, I'm also seeing,

```
Error: Marathon API error: Object is not valid (path: '/ipAddress' errors: ipAddress/discovery is not allowed for Docker containers using BRIDGE or USER networks)
```

**Comment by yathi-naik** [comment]
Using SetIPAddressPerTask() did not help either.

**Comment by timoreimann** [comment]
Hi @yathi-naik, issue should be fixed. Could you double-check on your end please? Thanks!

**Comment by yathi-naik** [comment]
I encountered the error. Here's what I'm doing,

```	application.Container.Docker.Network = "USER"
	ipAddr := marathon.IPAddressPerTask{
		NetworkName: container.Network,
	}
	application.SetIPAddressPerTask(ipAddr)
```

```
Error: Marathon API error: Object is not valid (path: '/ipAddress' errors: ipAddress/discovery is not allowed for Docker containers using BRIDGE or USER networks)
```

**Comment by timoreimann** [comment]
@yathi-naik did you try the latest master? I should have fixed this two days ago (see my previous message). The referenced PR has exactly your fix.

**Comment by yathi-naik** [comment]
@timoreimann Sorry, the fix is correct. I had the wrong commit number.

**Comment by timoreimann** [comment]
No worries. Thanks for verifying.
