### ISSUE TITLE
Add Support for Pods (Marathon 1.4)

### ISSUE THREAD

**Issue by catherinetcai** [gambol99/go-marathon#271]
Marathon 1.4 added pods. They're special groups of containers that share networking and storage resources on a single Mesos agent.

Pods only support the Mesos containerizer and can be interacted with via the /v2/pods endpoints. From the Marathon documentation, sample POST/GET/DELETE:

``` 
$ curl -X POST -H "Content-type: application/json" -d@<mypod>.json http://<ip>:<port>/v2/pods <<EOF
 {
    "id": "/simplepod",
    "scaling": { "kind": "fixed", "instances": 1 },
    "containers": [
      {
        "name": "sleep1",
        "exec": { "command": { "shell": "sleep 1000" } },
        "resources": { "cpus": 0.1, "mem": 32 }
      }
    ],
    "networks": [ {"mode": "host"} ]
 }
 EOF
```

` curl GET http://<ip>:<port>/v2/pods/simplepod::status`

`curl -X DELETE http://<ip>:<port>/v2/pods/simplepod`

**Comment by timoreimann** [comment]
This has been addressed by now.
