### ISSUE TITLE
Fix typo in struct HealthCheck

### ISSUE THREAD

**Issue by zyfdegh** [gambol99/go-marathon#286]
## Source code
Branch: master
Commit: latest one 1b9c2582

## Issue
In file `health.go`, [Line 30][line30], there is a type error in struct HealthCheck 
```sh
type HealthCheck struct {
	// ...
	IgnoreHTTP1xx          *bool    `json:"ignoreHttp1xx,ommitempty"`
}
```

## Expectation
The tag `ommitempty` should be `omitempty`

[line30]: https://github.com/gambol99/go-marathon/blob/master/health.go#L30

**Comment by timoreimann** [comment]
Good catch, @zyfdegh! 

Would you mind submitting a pull request?

**Comment by zyfdegh** [comment]
Yeah, I'm on it @timoreimann

**Comment by timoreimann** [comment]
Fixed.
