### ISSUE TITLE
Library doesn't recover after all marathon nodes go down and brought back up.

### ISSUE THREAD

**Issue by sshkel** [gambol99/go-marathon#294]
I have noticed that there is no way for library to recover after all marathon nodes go down for a long time and the brought back to life.

apiCall will call buildAPIRequest that will only return a marathon member that has status set to memberStatusUp. The only thing that can mark nodes to be up is healthCheckNodes function which is called from markDown function.  So after getting a node from buildAPIRequest we proceed to call Do and then run a markDown on that host trigerring healthcheck to be run. If the host isn't there it will set the status of the node to be "down".
Consequently if all marathon nodes die, the status of each node will be set to down and we will get an error. So far working as designed. However, if we bring marathon back up(any node specified in the config) those statuses will never be set to Up again since before running healthcheck we always run this block. 
```// step: create the API request
request, member, err := r.buildAPIRequest(method, url, bytes.NewReader(requestBody))
if err != nil {
	return err
}
```
That function never checks if the host is actually up and relies solely on the status variable set by healthcheck. As none of the nodes have status up it will return "All marathon nodes are down" and exit never running healthcheck again.
There should be some logic that actually checks if any of the nodes came back up.

Let me know if anything is unclear or extra info is needed.
Cheers,
Stanis

**Comment by marco-jantke** [comment]
Do you have some real case that this is happening? Your description is not valid in this regard, that the `healthCheckNode` is actually calling `buildMarathonRequest` directly which does not know about cluster or whatever, you specify it directly a member of the cluster that should be called.

I tested exactly this behaviour and for me it was working as expected.

**Comment by timoreimann** [comment]
@sshkel the improvements were added only fairly recently. I suppose you have tried things with go-marathon HEAD?

**Comment by sshkel** [comment]
Yeah, my bad, i think I was working with the stale version. Repulled head and everything looks good.  Thanks for putting up with my stupidity, fellas.

**Comment by timoreimann** [comment]
No worries -- glad it's now working for you!
