### ISSUE TITLE
Application API should support `embed` arguments

### ISSUE THREAD

**Issue by Colstuwjx** [gambol99/go-marathon#303]
As the marathon official [documented](https://mesosphere.github.io/marathon/docs/rest-api.html#get-v2appsappidembedembed), we should have it in go-marathon client.

**Comment by timoreimann** [comment]
That's already possible. Example:

```go
v := url.Values{}
v.Add("embed", "apps.tasks")
applications, _ := p.marathonClient.Applications(v)
```

Anything you're missing?

**Comment by Colstuwjx** [comment]
Yes, sorry about that.
