### ISSUE TITLE
latest master fails to compile

### ISSUE THREAD

**Issue by iderdik** [gambol99/go-marathon#307]
go get yields
```
github.com/gambol99/go-marathon/subscription.go:184: stream.Close undefined (type *eventsource.Stream has no field or method Close)
```

which is odd because your CI seems to be passing.  I'm using golang 1.8.1 on mac and in a linux docker container. Am I missing additional dependencies?

**Comment by timoreimann** [comment]
@iderdik I suppose you haven't updated `github.com/donovanhide/eventsource` since we merged #282, which introduced the `Close` call (that was added to the eventsource library in donovanhide/eventsource#28).

Can you try `go get -u` to update the package and see if that helps?

**Comment by iderdik** [comment]
Updating the eventsource reference did the trick. Thanks!

**Comment by timoreimann** [comment]
Glad to hear!
