### ISSUE TITLE
Http client configuration no longer honored for event stream connections

### ISSUE THREAD

**Issue by mtweten** [gambol99/go-marathon#309]
I believe #297 may have introduced a non-passive change to SSE functionality. I was testing a custom build of Traefik using the master branch of go-marathon, and noticed that the SSL configuration in Traefik is no longer used when establishing the SSE connection to marathon using the latest go-marathon code.

This is because Traefik makes use of a custom HTTPClient to supply the SSL configuration, and it only knows about config.HTTPClient, not the new config.HTTPSSEClient. If a custom HTTPSSEClient is not supplied, would it make sense to default HTTPSSEClient to HTTPClient if a custom HTTPClient is supplied (instead of creating a default http sse client)?

**Comment by ondrej-smola** [comment]
There is problem with configuration of client.Timeout - you should set it on non-sse requests and it shoud not be set on sse requests. Setting sse client to non default client would not work as you should set client.Timeout and it would also set sseClient.Timeout which is invalid.

**Comment by timoreimann** [comment]
@ondrej-smola I actually believe that the problem @mtweten describes is not (strictly) related to timeouts.

When we introduced an HTTP client specific to SSE in #297, we implicitly assumed consumers would choose the right client. Unfortunately, there's a subtle change in behavior if you don't watch closely: If you continue to pass an `HTTPClient` to the configuration (as prior to #297), it is now only used for non-SSE communication. In the case of Traefik where [a TLS configuration will also be injected](https://github.com/containous/traefik/blob/92fb86b66ff8f866b04ca337e20b4857bd575e75/provider/marathon/marathon.go#L107-L120), that TLS configuration will be silently dropped for the SSE part.

**Comment by ondrej-smola** [comment]
@timoreimann i know, i just reacted to "If a custom HTTPSSEClient is not supplied, would it make sense to default HTTPSSEClient to HTTPClient if a custom HTTPClient is supplied".

**Comment by timoreimann** [comment]
Gotcha.

I think we'll have to take that into account and, when in doubt, return an error to the consumer.

I'll try to put something together.
