### ISSUE TITLE
When a member is marked down, we ping Marathon to death

### ISSUE THREAD

**Issue by iderdik** [gambol99/go-marathon#310]
In [markDown](https://github.com/gambol99/go-marathon/blob/15ea23e360abb8b25071e677aed344f31838e403/cluster.go#L119), we loop through a range of nodes (which results in each `n` being a value copy) and then set its status to `memberStatusDown`. However, because that is being set on the value only, the next api failure will result in reading the original  value `memberStatusUp` and spawning another go routine. The best way would be to change this  to: 
```
     for i, _ := range c.members {
		// step: check if this is the node and it's marked as up - The double  checking on the
		// nodes status ensures the multiple calls don't create multiple checks
		if c.members[i].status == memberStatusUp && c.members[i].endpoint == endpoint {
			c.members[i].status = memberStatusDown
			go c.healthCheckNode(c.members[i])
			break
		}
	}
```
We'r actually seeing our Marathon server being crushed by pings and this is our best guess as to what is happening. Am I missing something?

**Comment by iderdik** [comment]
What I was missing is the `members` is ` []*member` an array of pointers. 

I'm still stumped as to why we're getting a deluge of pings though.

**Comment by timoreimann** [comment]
@iderdik thanks for reporting. May I ask what version of Marathon you're using?

I'm vaguely speculating you might be subject to #308 as well.

**Comment by iderdik** [comment]
After delving in to our app a bit more, I discovered that we recreate the marathon Client when we hit a failure which then allows another go routine to be created. We just moved to 1.4.4 as well so #308 is definitely going to be an issue for us.
