### ISSUE TITLE
example in readme doesn't compile

### ISSUE THREAD

**Issue by chrispickard** [gambol99/go-marathon#332]
Hey, just wanted to let you know that I copied what's in the readme from "Creating a client" and "Listing the applications," and this did not compile. Specifically, `client.Applications` now takes an arg, the printf should contain a `%v` instead of `%s` and `assert` is not defined.

**Comment by timoreimann** [comment]
@chrispickard thanks for reporting. 👍 I'll try to submit a PR over the holidays unless someone beats me to it.

**Comment by timoreimann** [comment]
@chrispickard I fixed the problems you've mentioned and applied a few other improvements. Hopefully everything should be working now. If not, please report back.

Thanks again. 👏
