### ISSUE TITLE
wait_on_running in CreateApplication immediately times out

### ISSUE THREAD

**Issue by Christopher-Bradshaw** [gambol99/go-marathon#49]
This
```
if wait_on_running {
		return client.WaitOnApplication(application.ID, 0)
}
```
immediately times out. We should be able to pass a timeout time to WaitOnApplication. Perhaps changing wait_on_running to an int is easiest, and then.

```
if wait_on_running != 0 {
		return client.WaitOnApplication(application.ID, wait_on_running)
}
```

If you want to do this, I can submit a PR.

**Comment by gambol99** [comment]
Change the wait_on_running from a boolean to a time.Duration and pass through to WaitOnApplication() would make sense ... The fact it's terminating straight away is a bit odd though, as a value of zero passed to WaitOnApplication() is defaulted to DefaultDeploymentTimeout: time.Duration(300) * time.Second [config.go](https://github.com/gambol99/go-marathon/blob/master/config.go#L52)

what version of marathon you running?  and go?... did the app start or error out? ..  

```go
func (client *Client) CreateApplication(application *Application, wait_on_running bool) error {
	result := new(Application)
	client.log("Creating an application: %s", application)
	if err := client.apiPost(MARATHON_API_APPS, &application, result); err != nil {
		return err
	}
	// step: are we waiting for the application to start?
	if wait_on_running {
		return client.WaitOnApplication(application.ID, 0) <--
	}
	return nil
}
```

```go
func (client *Client) WaitOnApplication(name string, timeout time.Duration) error {
  // <--- clutching as straws, but perhaps different versions of go handle the value differently and evaluates > 0 thus wouldn't inherit the default 300??? 
	if timeout <= 0 { 
		timeout = client.config.DefaultDeploymentTimeout
	}
   ....
```

**Comment by Christopher-Bradshaw** [comment]
I took a closer look through your examples and realised that I was just not setting the client up correctly. I was initiating it with 
`client, _ := marathon.NewClient(marathon.Config{URL: url})` which of course meant that the DefaultDeploymentTimeout was not set.

Thanks for the response, and sorry for taking up your time.

**Comment by gambol99** [comment]
Perfect :-) ... thanks for getting back ..
