### ISSUE TITLE
create and update application not returning the response

### ISSUE THREAD

**Issue by bhameyie** [gambol99/go-marathon#50]
I noticed that in the current version the response from `UpdateApplication` or `CreateApplication` is only the error. For my use case, I would need these 2 operations to also return the deserialized `Application` (which is already available in those methods) so as to know the deployment ids.

**Comment by bhameyie** [comment]
An alternative could be to add to 2 other methods for Creating and Updating the application so as not to break folks already using the library

**Comment by gambol99** [comment]
Yep, it make's sense! - and it's kind of pointless for both Create and Update to both decode the response and never return it, which is the case now. I've pushed the PR #51 and will merge shortly

```go
func (client *Client) CreateApplication(application *Application, wait_on_running bool) error {
	result := new(Application)
	client.log("Creating an application: %s", application)
	if err := client.apiPost(MARATHON_API_APPS, &application, result); err != nil {
		return err
	}
        ..
```

**Comment by bhameyie** [comment]
Thanks!
