### ISSUE TITLE
Application.ApplicationOK doesn't check for expected number of tasks

### ISSUE THREAD

**Issue by iderdik** [gambol99/go-marathon#58]
In https://github.com/gambol99/go-marathon/blob/master/application.go#L337  the Application is marked OK if 0 tasks are running. There are times that a bad container is deployed and the application is marked ok if they all tasks are removed at the same time (while marathon retries them). 

Would it be possible to add a check to ensure that the number of running tasks matches the expected number of tasks? I'm not sure where to get that expected number of tasks from or I'd open the PR myself.

**Comment by gambol99** [comment]
Sorry for the delay ... Admittedly i'm not sure how best to get these numbers either ... I'll have a look into it though ..

**Comment by gambol99** [comment]
Might be overthinking it ... perhaps just checking the tasks count == application instances requested when deployed is enough. Though i recall there was an if the application is deployed via a group, as internally marathon set the .instances variable to zero and use's as a means to control dependencies 

```go
// step: does the number of tasks match the number of tasks?
if !application.AllTaskRunning() {
	return false, nil
}
```
and the AllTaskRunning() method
```go
func (application *Application) AllTaskRunning() bool {
	if application.Instances == 0 {
		return true
	}
	if application.Tasks == nil {
		return false
	}
	if application.TasksRunning == application.Instances {
		return true
	}
	return false
}

```

**Comment by iderdik** [comment]
That check does seem like it should work. I guess I'll need to make multiple calls to make sure the tasks stay running for a few seconds.

**Comment by timoreimann** [comment]
This seems fixed, so I'm closing the ticket. Please reopen in case there's still something missing.
