### ISSUE TITLE
generic logger 

### ISSUE THREAD

**Issue by gambol99** [gambol99/go-marathon#66]
Implement a generic logger interface, defaulting to glog but allowing the consumer to override and run their own ..

**Comment by x-cray** [comment]
BTW, how `config.LogOutput` is actually used?

**Comment by eicca** [comment]
I assume it's not used any more. All logging is done with `glog` currently which is a bit inflexible.

**Comment by x-cray** [comment]
Ok, I removed its assignment from examples code in #79

**Comment by gambol99** [comment]
@x-cray, it was left over from the previous logging code ... although this issue is supposed act as a reminder to replace that as well :-) ..

**Comment by mattes** [comment]
We are using a customized glog version. As soon as we include another package that imports the "original" glog version, we get a panic: 

```
panic:
xxx.test flag redefined: log_dir
```

... which makes sense. Not sure how to solve this, yet.

**Comment by mattes** [comment]
Maybe this helps: https://github.com/golang/glog/blob/master/glog.go#L914

**Comment by eicca** [comment]
@mattes I think the best solution would be to not to use `glog` directly, rather injecting logger to the library through config.
I know that it was done in `grpc-go` for example: https://github.com/grpc/grpc-go/tree/master/grpclog
We can do the same, though maybe there are some better practices?

**Comment by mattes** [comment]
ref: #103
