### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by Raffo** [gambol99/go-marathon#78]
I wanted to improve the current implementation of the error handling. To do this, I had to get rid of the simple handling that was in place till now. I'm working on a separate branch, we can discuss this in the following PR: https://github.com/gambol99/go-marathon/pull/77 

PLEASE DO NOT MERGE THE PR! I want to discuss this with the community and understand how to proceed. We can maybe also think to schedule it for a major (breaking) release.

**Comment by Raffo** [comment]
This could be already a step in a much more minimal direction: https://github.com/Raffo/go-marathon/commit/bc23d5ae0467b23776c18b633c93f08473a78164 

@eicca please have a look.

**Comment by mattes** [comment]
Related to #101

**Comment by timoreimann** [comment]
I'd suggest to either rephrase the ticket to a more specific feature request/bug or close it as there's nothing too concrete in here we can base further discussions/implementations on.

**Comment by Raffo** [comment]
@timoreimann  We can continue in your issue (it's more active) even if this is older. I close the issue.
