### ISSUE TITLE
Golint conformance

### ISSUE THREAD

**Issue by x-cray** [gambol99/go-marathon#80]
I'm opening this issue here for discussion on the subject. @eicca suggested (https://github.com/gambol99/go-marathon/pull/79#issuecomment-152015182) that we might consider making project code meet golint rules. However, there are many places which are not just simply missing doc comments but require renaming of exported names. This will definitely be a breaking change. So, two questions here:
* Do we introduce a versioning strategy? (Also to track Marathon API changes)
* Do we try to make code meet golint rules?

**Comment by eicca** [comment]
> Do we introduce a versioning strategy? (Also to track Marathon API changes)
I think at this stage it would be nice to have some versioning and to have a simple changelog at least.

> Do we try to make code meet golint rules?
In my opinion it definitely makes sense. I started making changes some time ago here: https://github.com/eicca/go-marathon/commit/cc88c7f66dc2e2a167aae98183a22af2894187df but then I realized that there's much more to change, so I got lazy a bit :/

**Comment by eicca** [comment]
There are two things left:
- events.go
- eventsource `Event.Id()` method
