### ISSUE TITLE
Filter getTasks by status

### ISSUE THREAD

**Issue by emilevauge** [gambol99/go-marathon#81]
Hi!
Marathon's API allows to filter by status when retrieving tasks:
https://mesosphere.github.io/marathon/docs/rest-api.html#get-v2-tasks
It would be great to add that possibility here https://github.com/gambol99/go-marathon/blob/master/task.go#L59 by adding a parameter `status string` to the method `func (r *marathonClient) AllTasks() (*Tasks, error)`.
For now, it's impossible to get tasks' status with `gambol99/go-marathon`.

**Comment by eicca** [comment]
Makes sense!
It should also affect `ListTasks` https://github.com/gambol99/go-marathon/blob/master/task.go#L80 I think. To be honest I would prefer to get rid of the `ListTasks` as it's just a simple data manipulation.

**Comment by eicca** [comment]
@emilevauge I just pushed the changes to master. Can you please check if it solves the issue now?

**Comment by emilevauge** [comment]
@eicca, great! I Will test that on [traefik](http://github.com/emilevauge/traefik) ASAP :)

**Comment by gambol99** [comment]
closing the issue as solved?

**Comment by emilevauge** [comment]
Yep :) Solved. Thanks!
