### ISSUE TITLE
HasApplication uses ListApplications and retrieves entire state of marathon 

### ISSUE THREAD

**Issue by tracycodes** [gambol99/go-marathon#95]
When using the HasApplication function go-marathon queries through to marathon with the `apps` endpoint. In deployments with large numbers of applications this causes marathon to return a significant amount of data. Functionally, HasApplication seems nearly equivalent to Application (it just handles the ErrDoesNotExist error by returning a falsey value). 

Is there any difference between the approach I describe and the current implementation with ListApplications?

If not, I'm happy to submit a PR to improve this. Thanks!

**Comment by timoreimann** [comment]
IMHO, there shouldn't be any functional difference. Replacing the existing implementation by a call to `Application(name)` (which maps to a REST call against `/apps/:appId` directly) sounds reasonable and more economic to me.

**Comment by gambol99** [comment]
@tracycodes .. yep! make's sense, the iteration of the apps isn't ideal at all. We can call Application(), if error, check for ErrDoesNotExist i.e. return false .. and any another errors passed straight back ... A PR would be most welcome :-)
